
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${spring.security.oauth2.client.registration.google.client-id}
            client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
            scope:
                          - openid
                          - profile
                          - email
            redirect-uri: ${app.google.oauth2.redirect-uri}
        provider:
          google:
            authorization-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_AUTHORIZATION_URI}
            token-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_TOKEN_URI}
            user-info-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_USER_INFO_URI}
            user-name-attribute: ${SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_GOOGLE_USER_NAME_ATTRIBUTE}
            server:
              port: 8080

